"""Email digest functionality for opportunity notifications."""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import logging

from jinja2 import Template

from ..models import ScoredResults, Opportunity
from ..config import settings

logger = logging.getLogger(__name__)


# HTML email template
EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; text-align: center; }
        .header h1 { margin: 0; font-size: 24px; }
        .header p { margin: 10px 0 0; opacity: 0.9; }
        .stats { display: flex; justify-content: space-around; padding: 15px; background: #f8f9fa; border-bottom: 1px solid #eee; }
        .stat { text-align: center; }
        .stat-value { font-size: 24px; font-weight: bold; color: #667eea; }
        .stat-label { font-size: 12px; color: #666; }
        .opportunities { padding: 20px; }
        .opportunity { border: 1px solid #eee; border-radius: 8px; padding: 15px; margin-bottom: 15px; }
        .opportunity:hover { border-color: #667eea; }
        .opp-header { display: flex; justify-content: space-between; align-items: start; margin-bottom: 10px; }
        .opp-title { font-size: 16px; font-weight: 600; color: #333; text-decoration: none; }
        .opp-title:hover { color: #667eea; }
        .score { padding: 4px 12px; border-radius: 12px; font-size: 14px; font-weight: bold; }
        .score-high { background: #d4edda; color: #155724; }
        .score-med { background: #fff3cd; color: #856404; }
        .score-low { background: #f8d7da; color: #721c24; }
        .opp-meta { display: flex; gap: 15px; font-size: 13px; color: #666; margin-bottom: 8px; }
        .opp-desc { font-size: 14px; color: #555; line-height: 1.5; }
        .keywords { margin-top: 8px; }
        .keyword { display: inline-block; background: #e9ecef; padding: 2px 8px; border-radius: 4px; font-size: 12px; margin: 2px; }
        .footer { padding: 20px; background: #f8f9fa; text-align: center; font-size: 12px; color: #666; }
        .cta { display: inline-block; background: #667eea; color: white; padding: 8px 20px; border-radius: 4px; text-decoration: none; margin: 5px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎯 LFG Opportunity Digest</h1>
            <p>{{ date }}</p>
        </div>

        <div class="stats">
            <div class="stat">
                <div class="stat-value">{{ total_found }}</div>
                <div class="stat-label">Total Found</div>
            </div>
            <div class="stat">
                <div class="stat-value">{{ high_score_count }}</div>
                <div class="stat-label">Score 85+</div>
            </div>
            <div class="stat">
                <div class="stat-value">${{ total_value|int }}k</div>
                <div class="stat-label">Est. Value</div>
            </div>
        </div>

        <div class="opportunities">
            {% for opp in opportunities %}
            <div class="opportunity">
                <div class="opp-header">
                    <a href="{{ opp.url }}" class="opp-title">{{ opp.title }}</a>
                    <span class="score {% if opp.total_score >= 85 %}score-high{% elif opp.total_score >= 70 %}score-med{% else %}score-low{% endif %}">
                        {{ opp.total_score|int }}
                    </span>
                </div>
                <div class="opp-meta">
                    <span>💰 {{ opp.budget_display }}</span>
                    {% if opp.client and opp.client.rating %}
                    <span>⭐ {{ opp.client.rating|round(1) }}</span>
                    {% endif %}
                    <span>📍 {{ opp.source.value|title }}</span>
                </div>
                <div class="opp-desc">{{ opp.description[:200] }}{% if opp.description|length > 200 %}...{% endif %}</div>
                {% if opp.matched_keywords %}
                <div class="keywords">
                    {% for kw in opp.matched_keywords[:5] %}
                    <span class="keyword">{{ kw }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>

        <div class="footer">
            <p>Generated by LFG Opportunity Finder</p>
            <p>
                <a href="https://lfgconsultants.com" class="cta">Visit LFG Consultants</a>
            </p>
        </div>
    </div>
</body>
</html>
"""


def create_email_content(results: ScoredResults, max_opportunities: int = 10) -> str:
    """Generate HTML email content from results."""
    opportunities = results.opportunities[:max_opportunities]

    # Calculate estimated total value
    total_value = 0
    for opp in opportunities:
        budget = opp.budget_max or opp.budget_min or 0
        if opp.hourly_max:
            budget = opp.hourly_max * 40  # Estimate 40 hours
        total_value += budget

    template = Template(EMAIL_TEMPLATE)
    return template.render(
        date=datetime.now().strftime("%B %d, %Y"),
        total_found=results.total_fetched,
        high_score_count=sum(1 for o in results.opportunities if o.total_score >= 85),
        total_value=total_value / 1000,
        opportunities=opportunities
    )


def send_digest(results: ScoredResults, max_opportunities: int = 10) -> bool:
    """Send email digest of top opportunities.

    Returns True if email was sent successfully.
    """
    if not settings.smtp_user or not settings.email_to:
        logger.warning("Email not configured. Set SMTP_USER and EMAIL_TO in .env")
        return False

    if not results.opportunities:
        logger.info("No opportunities to send in digest")
        return False

    try:
        # Create message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"🎯 LFG Opportunities: {len(results.opportunities)} matches found"
        msg["From"] = settings.email_from
        msg["To"] = settings.email_to

        # Plain text fallback
        text_content = f"""
LFG Opportunity Finder - {datetime.now().strftime('%B %d, %Y')}

Found {results.total_fetched} opportunities, {len(results.opportunities)} match your criteria.

Top Opportunities:
"""
        for i, opp in enumerate(results.opportunities[:max_opportunities], 1):
            text_content += f"\n{i}. {opp.title}\n"
            text_content += f"   Score: {opp.total_score:.0f} | Budget: {opp.budget_display}\n"
            text_content += f"   URL: {opp.url}\n"

        msg.attach(MIMEText(text_content, "plain"))

        # HTML content
        html_content = create_email_content(results, max_opportunities)
        msg.attach(MIMEText(html_content, "html"))

        # Send
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            server.starttls()
            server.login(settings.smtp_user, settings.smtp_password)
            server.send_message(msg)

        logger.info(f"Digest sent to {settings.email_to}")
        return True

    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False


def test_email_config() -> bool:
    """Test email configuration without sending."""
    if not settings.smtp_user:
        return False

    try:
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            server.starttls()
            server.login(settings.smtp_user, settings.smtp_password)
        return True
    except Exception as e:
        logger.error(f"Email config test failed: {e}")
        return False
